import re
import requests
from youtube_transcript_api import YouTubeTranscriptApi

def extract_video_id(url: str) -> str:
    """
    Extracts the YouTube video ID from a given URL.
    Handles standard youtube.com and youtu.be URLs.
    """
    regex = r"(?:v=|\/|youtu\.be\/|v\/|embed\/)([0-9A-Za-z_-]{11})"
    match = re.search(regex, url)
    if match:
        return match.group(1)
    return None

def clean_vtt(vtt_text: str) -> str:
    """Removes WEBVTT metadata, styling, and timestamps from a raw .vtt file."""
    lines = vtt_text.split('\n')
    cleaned = []
    for line in lines:
        if line.startswith('WEBVTT') or '-->' in line or line.startswith('Kind:') or line.startswith('Language:') or line.startswith('Style:'):
            continue
        line = re.sub(r'<[^>]*>', '', line)
        line = re.sub(r'align:start position:\d+%', '', line)
        if line.strip().isdigit():
            continue
        if line.strip() and "Subscribe" not in line:
            cleaned.append(line.strip())
    
    # Remove duplicate consecutive lines
    final_cleaned = []
    for p in cleaned:
        if not final_cleaned or final_cleaned[-1] != p:
            final_cleaned.append(p)
            
    return " ".join(final_cleaned).replace("\n", " ").strip()

def fallback_fetch_with_piped(video_id: str) -> str:
    """Uses the open-source Piped video proxy instance to fetch VTT subtitles robustly."""
    # List of resilient public piped API instances
    instances = [
        "https://pipedapi.kavin.rocks",
        "https://pipedapi.in.projectsegfau.lt",
        "https://pipedapi.adminforge.de"
    ]
    
    for instance_url in instances:
        try:
            res = requests.get(f"{instance_url}/streams/{video_id}", timeout=10)
            if res.status_code == 200:
                data = res.json()
                subtitles = data.get("subtitles", [])
                
                # Find best english subtitle
                en_sub_url = None
                for sub in subtitles:
                    code = sub.get("code", "").lower()
                    name = sub.get("name", "").lower()
                    if "en" in code or "english" in name:
                        en_sub_url = sub.get("url")
                        # priorize manual over auto
                        if not sub.get("autoGenerated"):
                            break
                            
                if en_sub_url:
                    sub_res = requests.get(en_sub_url, timeout=10)
                    if sub_res.status_code == 200:
                        return clean_vtt(sub_res.text)
        except Exception:
            continue # Try next instance
            
    raise Exception("Piped API fallback exhausted. No English captions found or all proxies blocked.")

def fetch_transcript(video_id: str) -> str:
    """
    Fetches the transcript natively using youtube-transcript-api.
    If blocked by YouTube Cloud IP ban logic, auto-reroutes to Piped API instances.
    """
    try:
        try:
            transcript_data = YouTubeTranscriptApi.get_transcript(video_id)
        except AttributeError:
            api = YouTubeTranscriptApi()
            transcript_list = api.list(video_id)
            transcript_data = transcript_list.find_transcript(['en']).fetch()

        text_parts = []
        for item in transcript_data:
            if isinstance(item, dict) and 'text' in item:
                text_parts.append(item['text'])
            elif hasattr(item, 'text'):
                text_parts.append(item.text)
                
        if not text_parts:
            raise Exception("No transcript items parsed.")
            
        return " ".join(text_parts).replace("\n", " ").strip()
        
    except Exception as e:
        error_msg = str(e).lower()
        if "could not retrieve a transcript" in error_msg or "blocked" in error_msg or "ip" in error_msg or "bot" in error_msg:
            print("Native API IP-Blocked. Booting Piped API proxy fallback...")
            return fallback_fetch_with_piped(video_id)
        else:
            print("Native API failed, attempting immediate fallback to Piped API...")
            return fallback_fetch_with_piped(video_id)
